"""Add is_admin field to User model

Revision ID: 508d6336a83b
Revises: 23570ec15b2c
Create Date: 2024-12-12 19:28:31.474209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508d6336a83b'
down_revision = '23570ec15b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
