"""Add Alert model

Revision ID: 570e423da08f
Revises: 508d6336a83b
Create Date: 2024-12-16 21:03:15.583559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570e423da08f'
down_revision = '508d6336a83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('device')
    op.drop_table('monitoring_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hostname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=15), nullable=False),
    sa.Column('mac_address', sa.VARCHAR(length=17), nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('alert')
    # ### end Alembic commands ###
